version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: serverpod_example
      POSTGRES_PASSWORD: "k92IqNTkGePwOL5VBWBE4MGq8uXOx_pW"
    volumes:
      - serverpod_example_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "WGikjqsUG7_2LoVAu5qdInDMLtmhqI7a"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  serverpod_example_data:
